services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

volumes:
  postgres_data:
