name: Linting

on: [pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run linting with Prettier
        run: npm run lint:prettier:check

  eslint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run linting with eslint
        run: npm run lint:eslint:check

  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
