name: Linting

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run linting with Prettier
        run: npm run lint:prettier:check
