name: Automated Tests

on: [pull_request]

jobs: 
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts/hydrogen
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          
      - name: Install dependencies with npm ci
        run: npm ci

      - name: Run tests
        run: npm test
